### ISSUE TITLE
Error：“property missing ':'” when I use background and svg together

### ISSUE THREAD

**Issue by blankPen** [remarkablemark/style-to-object#112]
## Expected Behavior

no Error, parse success

## Actual Behavior
An error exception has occurred

Error: undefined:1:1675: property missing ':'
    at m (index.js:103:15)
    at A (index.js:208:37)
    at index.js:239:20
    at c (index.js:250:10)
    at l (index.js:21:22)
    at ?editor_console=true:126:16

## Steps to Reproduce

Reference demo

## Reproducible Demo
https://jsfiddle.net/t6bkepf9/10/

## Environment

- Version: 0.4.1
- Platform: web
- Browser: chrome
- OS: mac os

**Comment by remarkablemark** [comment]
@blankPen the `background` property in your CSS style is invalid. See [JSFiddle](https://jsfiddle.net/remarkablemark/fcrd86g2/) render successful when `background` is removed.

**Comment by blankPen** [comment]
> 
In fact, the`background` property is not invalid， its value is a correct value；
You can check out the demo https://jsfiddle.net/t6bkepf9/10/, which shows a loading animation;
